name: Parse Filmarks Profile

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install cheerio

      - name: Fetch profile
        run: |
          curl \
            https://filmarks.com/users/rem_srem_jp \
            -o profile.html

      - name: Parse profile
        run: |
          node scripts/parse-profile.js