name: Parse Filmarks Profile

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install cheerio

      - name: Fetch all profiles
        run: |
          node scripts/fetch-all-profiles.js

      - name: Fetch all reviews
        run: |
          node scripts/fetch-review.js

      - name: Show first 5 reviews
        run: |
          node <<'EOF'
          const data =
            require("./review-details.json");

          console.log(
            JSON.stringify(
              data.slice(0, 5),
              null,
              2
            )
          );
          EOF