name: Test Filmarks Fetch

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: Fetch HTML
        run: |
          curl \
          https://filmarks.com/movies/116731/reviews/219754768 \
          -o review.html

      - name: Show first lines
        run: |
          head -100 review.html